#!/usr/bin/env node
// RestaurantOS - Local Setup Script
// Run: node setup.js

import { readFileSync, writeFileSync, existsSync } from "fs";
import { execSync } from "child_process";
import readline from "readline";

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const question = (q) => new Promise((resolve) => rl.question(q, resolve));

console.log("\n========================================");
console.log("  RestaurantOS - Local Setup");
console.log("========================================\n");

// Check if .env already exists
if (existsSync(".env")) {
  console.log(".env file already exists. Skipping creation.");
  console.log("If you want to recreate it, delete .env first and run this script again.\n");
} else {
  console.log("Step 1: Creating .env file...\n");

  console.log("You need your TiDB Cloud connection string.");
  console.log("1. Go to https://tidbcloud.com > your cluster > Connect");
  console.log("2. Select 'Node.js' as the framework");
  console.log("3. Copy the connection string (starts with mysql://)\n");

  const dbUrl = await question("Paste your TiDB Cloud connection string: ");

  if (!dbUrl || !dbUrl.startsWith("mysql://")) {
    console.error("\nERROR: Invalid connection string. Must start with mysql://");
    console.error("Run this script again with the correct URL.");
    process.exit(1);
  }

  const envContent = `# Auto-generated by setup.js
APP_ID=19f11fe0-7372-819a-8000-00004245aaec
APP_SECRET=vkelQyu5cn7jcTS2pWeeemNOsoyBSQrP
VITE_APP_ID=19f11fe0-7372-819a-8000-00004245aaec
VITE_KIMI_AUTH_URL=https://auth.kimi.com
KIMI_AUTH_URL=https://auth.kimi.com
KIMI_OPEN_URL=https://open.kimi.com
OWNER_UNION_ID=d7uvjj1g6i8qbdk3t8rg
DATABASE_URL=${dbUrl.trim()}
PORT=3000
`;

  writeFileSync(".env", envContent);
  console.log("\n.env file created successfully!\n");
}

// Check node_modules
console.log("Step 2: Checking dependencies...");
if (!existsSync("node_modules")) {
  console.log("Running npm install (this may take 2-3 minutes)...");
  console.log("If it hangs, try: npm install --prefer-offline\n");
  try {
    execSync("npm install", { stdio: "inherit" });
  } catch (e) {
    console.error("\nnpm install failed. Try these fixes:");
    console.error("  1. Clear cache: npm cache clean --force");
    console.error("  2. Use different registry: npm config set registry https://registry.npmmirror.com");
    console.error("  3. Try with: npm install --prefer-offline");
    process.exit(1);
  }
} else {
  console.log("node_modules already exists. Skipping npm install.");
  console.log("If you want fresh install, delete node_modules and run again.\n");
}

// Push database schema
console.log("\nStep 3: Pushing database schema...");
try {
  execSync("npm run db:push", { stdio: "inherit" });
  console.log("Database schema pushed!\n");
} catch (e) {
  console.error("\nDatabase push failed. Check your DATABASE_URL in .env");
  console.error("Make sure your TiDB cluster is running and the URL is correct.");
  process.exit(1);
}

// Seed data
console.log("\nStep 4: Seeding test data...");
try {
  execSync("npx tsx db/seed.ts", { stdio: "inherit" });
  console.log("Test data seeded!\n");
} catch (e) {
  console.error("\nSeed failed. The database schema may already have data.");
  console.error("You can skip this step and run the app.");
}

console.log("\n========================================");
console.log("  Setup Complete!");
console.log("========================================");
console.log("\nStart the app:");
console.log("  npm run dev");
console.log("\nThen open: http://localhost:3000");
console.log("\nLogin with Kimi OAuth (the button on the login page).");
console.log("\nTo build Android APK:");
console.log("  cd android && ./gradlew assembleDebug");
console.log("\n========================================\n");

rl.close();
